[llm.claude]
type = "anthropic"

[worker.app]
url = "http://localhost:4444"

[agent.my-agent]
llm = "claude"
model = "claude-haiku-4-5-20251001"
worker = "app"

[serve]
auth = false

[agent.my-agent.slack]
name = "My Agent"
