# generated by datamodel-codegen:
#   filename:  protocol.schema.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Dict, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Announce(Enum):
    auto = 'auto'
    never = 'never'


class Approve1(Enum):
    never = 'never'
    always = 'always'


class AudioData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    format: str


class AuthFailure(Enum):
    interrupt = 'interrupt'
    degrade = 'degrade'


class ClientInput4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    args: Any | None = None
    name: str
    turn_id: str | None = None
    type: Literal['client.action']


class ClientInput5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resume']


class ClientInput7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    error: str
    id: str
    retryable: bool
    type: Literal['tool.error']


class ClientPayload4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any | None = None
    name: str
    type: Literal['client.action']


class ContentPart1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    type: Literal['text']


class ContentPart4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_audio: AudioData
    type: Literal['input_audio']


class DecisionAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    id: str | None = None
    response: Annotated[
        Any,
        Field(
            description="A neutral `LlmResponse`, or the provider's native response when the\nanswered `llm.execute` carried a `format`."
        ),
    ]
    type: Literal['llm.result']


class DecisionAction9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str | None = None
    payload: Any | None = None
    reason: str
    type: Literal['interrupt']


class DecisionAction10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resolve']


class DecisionAction11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Annotated[
        str,
        Field(
            description='Where a connection is declared: `mcp.<id>` or `plugin.<id>.mcp.<server>`'
        ),
    ]
    type: Literal['connector.sync']


class DecisionAction12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: Any | None = None
    type: Literal['done']


class DecisionTrigger1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.start']


class DecisionTrigger3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any | None = None
    name: str
    type: Literal['client.action']


class DecisionTrigger9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resumed']


class DeferToolsStrategy(Enum):
    search = 'search'


class EffectKind1(Enum):
    tool_call = 'tool_call'
    sub_agent = 'sub_agent'
    llm_call = 'llm_call'


class EffectStatus1(Enum):
    pending = 'pending'
    completed = 'completed'
    failed = 'failed'
    retry_scheduled = 'retry_scheduled'
    queued = 'queued'


class ErrorCode(Enum):
    provider_error = 'provider_error'
    rate_limited = 'rate_limited'
    refused = 'refused'
    budget_exceeded = 'budget_exceeded'
    deadline_exceeded = 'deadline_exceeded'
    invalid_response = 'invalid_response'
    handler_error = 'handler_error'
    worker_unreachable = 'worker_unreachable'
    unroutable = 'unroutable'
    internal = 'internal'


class ErrorInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: ErrorCode
    detail: Annotated[
        Any | None,
        Field(
            description='Small structured particulars: a status, the llm blocks that exist.'
        ),
    ] = None
    message: Annotated[
        str,
        Field(
            description='One engine-authored sentence, safe to show a human. Never a raw\ndocument — an unbounded body belongs in the log.'
        ),
    ]
    param: Annotated[
        str | None,
        Field(
            description="The one input to go and fix, when the failure names one: `agent.llm`,\n`actions[0].type`. Stripe's `param`."
        ),
    ] = None


class FileData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_data: str
    filename: str


class Handler(Enum):
    server = 'server'
    worker = 'worker'
    client = 'client'


class ImageUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class InterruptOption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    label: str
    style: Annotated[
        str | None,
        Field(description='`primary` or `danger`; anything else renders plain.'),
    ] = None
    value: Annotated[
        Any,
        Field(
            description="Delivered verbatim as the resolution's `payload`; worker vocabulary."
        ),
    ]


class InterruptOrigin(Enum):
    system = 'system'
    operator = 'operator'
    machine = 'machine'
    frontend = 'frontend'


class InterruptPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expiresAt: Annotated[
        str | None, Field(description='RFC 3339; display only until engine TTLs land.')
    ] = None
    message: Annotated[
        str | None,
        Field(
            description="Markdown; channels down-convert. Without it, channels fall back to\nthe interrupt's `reason`."
        ),
    ] = None
    metadata: Annotated[
        Any | None,
        Field(
            description='Free-form, delivered to clients verbatim. `metadata.options`\n([`InterruptOption`] list) renders as Slack buttons.'
        ),
    ] = None
    responseSchema: Annotated[
        Any | None,
        Field(description='JSON Schema for the expected resolution payload.'),
    ] = None
    toolCallId: Annotated[
        str | None, Field(description='Binds the interrupt to a prior tool call.')
    ] = None


class InterruptResponder(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    channel: Annotated[
        str, Field(description='The channel kind, e.g. `slack`, `ag-ui`.')
    ]
    label: Annotated[
        str | None,
        Field(description="The chosen option's label, when the resolution was a pick."),
    ] = None
    style: Annotated[
        str | None,
        Field(
            description="The chosen option's `style`, when the resolution was a pick."
        ),
    ] = None
    user: Annotated[str | None, Field(description='Channel-native user id.')] = None


class LlmFormat(Enum):
    openai = 'openai'
    anthropic = 'anthropic'


class LlmTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defer: Annotated[
        bool | None,
        Field(
            description="Keep this definition out of the request.\n\nThe engine still records it, still routes a call to it, and still finds\nit in a search. Only the request omits it, which is what keeps a large\ntool set out of the model's context and out of the cached prefix.\n\nAny source can set it: a tool the config declares, a connection, or\nwhatever comes next. Deferral is a property of a tool, not of where it\ncame from."
        ),
    ] = None
    description: str
    input: Annotated[
        Any | None,
        Field(
            description="JSON Schema for the tool's arguments; omitted declares a no-argument\ntool. The engine validates each call's arguments against it and hands\nproviders their native form."
        ),
    ] = None
    name: str
    output: Annotated[
        Any | None,
        Field(
            description='JSON Schema the settled result must satisfy; never sent to the model.\nA violating result settles as a terminal tool error.'
        ),
    ] = None


class McpTools(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defer: Annotated[
        bool | None,
        Field(
            description="Keep every surviving tool out of the request. See [`LlmTool::defer`].\nAbsent ⇒ the agent's `defer_tools`."
        ),
    ] = None
    exclude: list[str] | None = None
    idempotent: bool | None = None
    include: list[str] | None = None
    non_destructive: bool | None = None
    read_only: bool | None = None


class ReasoningEffort(Enum):
    xhigh = 'xhigh'
    high = 'high'
    medium = 'medium'
    low = 'low'
    minimal = 'minimal'
    none = 'none'


class ReasoningProvider(Enum):
    anthropic = 'anthropic'
    openai = 'openai'
    openrouter = 'openrouter'


class ResourceContents(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blob: str | None = None
    mimeType: str | None = None
    text: str | None = None
    uri: str


class ResponseImage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class ResumeStatus(Enum):
    resolved = 'resolved'
    cancelled = 'cancelled'


class RetryOverride(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backoff_base_secs: Annotated[int | None, Field(ge=0)] = None
    backoff_max_secs: Annotated[int | None, Field(ge=0)] = None
    max_attempts: Annotated[int | None, Field(ge=0)] = None
    queue_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    run_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    total_timeout_secs: Annotated[int | None, Field(ge=0)] = None


class RetryPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backoff_base_secs: Annotated[int, Field(ge=0)]
    backoff_max_secs: Annotated[int, Field(ge=0)]
    max_attempts: Annotated[
        int,
        Field(
            description='Cap on total attempts, not on retries: `1` allows one try and no retry.',
            ge=0,
        ),
    ]
    queue_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    run_timeout_secs: Annotated[int | None, Field(ge=0)] = None
    total_timeout_secs: Annotated[int | None, Field(ge=0)] = None


class Role(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class SkillMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    name: str


class StoredContent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    type: Literal['text']


class StoredContent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['blob']
    uri: str


class StoredContent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mimeType: str | None = None
    name: str | None = None
    type: Literal['link']
    uri: str


class StoredResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: list[StoredContent1 | StoredContent2 | StoredContent3] | None = None
    isError: bool | None = None
    structuredContent: Any | None = None


class SubAgent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    id: str


class Subject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    issuer: Annotated[
        str,
        Field(
            description="Where a person's name comes from — `slack`, `app`, `cli`, or whatever a\ndeployment registers. Stamped by whatever authenticated the request, and\nnever read out of one: a caller free to name its own issuer could name\nanother source's people.",
            title='Issuer',
        ),
    ]


class ToolCallChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str | None = None
    id: str
    name: str | None = None


class ToolCallFunction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str
    name: str


class ToolContent1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    type: Literal['text']


class ToolContent2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    mimeType: str
    type: Literal['image']


class ToolContent3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    mimeType: str
    type: Literal['audio']


class ToolContent4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    resource: ResourceContents
    type: Literal['resource']


class ToolContent5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mimeType: str | None = None
    name: str | None = None
    type: Literal['resource_link']
    uri: str


class ToolInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['valid']
    value: Any


class ToolInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str
    status: Literal['invalid']
    value: Any


class ToolInput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str
    status: Literal['malformed']


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache_read: Annotated[
        int,
        Field(
            description='The part of `input` the provider read from the cache.', ge=0
        ),
    ]
    cache_write: Annotated[
        int,
        Field(description='The part of `input` the provider wrote to the cache.', ge=0),
    ]
    input: Annotated[
        int, Field(description='Every input token of the call, cached or not.', ge=0)
    ]
    output: Annotated[int, Field(ge=0)]
    provider: Annotated[
        Any | None,
        Field(
            description='The counts as the provider reported them, for a reader that wants a\nnumber this type does not name.'
        ),
    ] = None
    total: Annotated[int, Field(description='`input` and `output` together.', ge=0)]
    uncached_input: Annotated[
        int, Field(description='The part of `input` the provider read fresh.', ge=0)
    ]


class VideoUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class Visibility(Enum):
    shared = 'shared'
    private = 'private'


class WorkerIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    metadata: dict[str, str]
    subject: Subject | None = None
    visibility: Visibility | None = None


class AgentPlugin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approve: Annotated[
        Approve1 | Literal['destructive'] | None,
        Field(
            description="Which of a connection's calls stop for a person.",
            title='Approve',
        ),
    ] = None
    auth_failure: AuthFailure | None = None
    description: str | None = None
    id: str
    servers: Annotated[
        list[str] | None,
        Field(description="Where each of this plugin's servers is declared."),
    ] = None
    skills: list[SkillMeta] | None = None
    tools: Annotated[
        McpTools | None, Field(description="Applied to each of the plugin's servers.")
    ] = None


class AgentTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    defer: Annotated[
        bool | None,
        Field(
            description="Keep this tool out of the request. See [`LlmTool::defer`]. Absent ⇒\nthe agent's `defer_tools`."
        ),
    ] = None
    description: str | None = None
    handler: Handler | None = None
    input: Any | None = None
    name: str
    output: Any | None = None


class ClientContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context: list[Any] | None = None
    forwarded_props: Any | None = None
    state: Any | None = None
    tools: list[AgentTool] | None = None


class ClientInput6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    content: (
        list[ToolContent1 | ToolContent2 | ToolContent3 | ToolContent4 | ToolContent5]
        | None
    ) = None
    id: str
    is_error: bool | None = None
    result: Any | None = None
    structured_content: Any | None = None
    type: Literal['tool.result']


class ContentPart2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image_url: ImageUrl
    type: Literal['image_url']


class ContentPart3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file: FileData
    type: Literal['file']


class ContentPart5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['video_url']
    video_url: VideoUrl


class ContentPart(
    RootModel[ContentPart1 | ContentPart2 | ContentPart3 | ContentPart4 | ContentPart5]
):
    root: Annotated[
        ContentPart1 | ContentPart2 | ContentPart3 | ContentPart4 | ContentPart5,
        Field(title='ContentPart'),
    ]


class DecisionAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: Any
    id: str | None = None
    name: str
    retry: Annotated[
        RetryOverride | None,
        Field(
            description="Layered over the agent config's policy for this kind, else over the\nengine's default for where the tool runs."
        ),
    ] = None
    type: Literal['tool.call']


class DecisionAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    content: (
        list[ToolContent1 | ToolContent2 | ToolContent3 | ToolContent4 | ToolContent5]
        | None
    ) = None
    id: str | None = None
    is_error: bool | None = None
    result: Any | None = None
    structured_content: Any | None = None
    type: Literal['tool.result']


class DecisionAction5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    code: ErrorCode | None = None
    detail: Any | None = None
    error: str
    id: str | None = None
    retryable: Annotated[bool | None, Field(description='Omitted ⇒ terminal.')] = None
    type: Literal['tool.error']


class DecisionAction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int | None, Field(ge=0)] = None
    code: ErrorCode | None = None
    detail: Any | None = None
    error: str
    id: str | None = None
    retryable: Annotated[bool | None, Field(description='Omitted ⇒ terminal.')] = None
    type: Literal['llm.error']


class DecisionTrigger4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str
    attempt: Annotated[int, Field(ge=0)]
    deadline: AwareDatetime | None = None
    id: str
    input: Annotated[
        ToolInput1 | ToolInput2 | ToolInput3,
        Field(
            description="The engine's classification of `arguments` against the tool's\ndeclared `input` schema: `valid` (with the parsed `value`),\n`invalid` (value plus the violation), or `malformed` (not a JSON\nobject). Always on the wire.",
            title='ToolInput',
        ),
    ]
    name: str
    type: Literal['tool.execute']


class DecisionTrigger5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: ErrorInfo | None = None
    id: str
    name: str
    ok: bool
    result: StoredResult | None = None
    type: Literal['tool.finished']


class DecisionTrigger6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: Annotated[int, Field(ge=0)]
    deadline: AwareDatetime | None = None
    format: LlmFormat | None = None
    id: str
    request: Annotated[
        Any,
        Field(
            description="The neutral `LlmRequest` JSON, or the provider's native request body\nwhen `format` is set."
        ),
    ]
    stream: bool
    type: Literal['llm.execute']


class DecisionTrigger8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    error: ErrorInfo | None = None
    id: str
    ok: bool
    result: str | None = None
    session_id: str
    type: Literal['sub_agent.finished']


class DecisionTrigger10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cost: Annotated[str | None, Field(pattern='^-?\\d+(\\.\\d+)?$')] = None
    data: Any | None = None
    turn_id: str
    type: Literal['turn.finished']
    usage: Usage | None = None


class DeferTools(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    max_matches: Annotated[
        int | None,
        Field(
            description='The most matches one search answers with. Never zero: a search that can\nanswer with nothing is a search the model cannot use.',
            ge=1,
        ),
    ] = None
    strategy: Annotated[
        DeferToolsStrategy | None,
        Field(description='Which tools the agent gets to reach the ones it defers.'),
    ] = None


class Effect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str | None = None
    anchor: Annotated[
        str | None, Field(description='The tree node the effect was requested at.')
    ] = None
    arguments: str | None = None
    attempt: Annotated[int, Field(ge=0)]
    deadline: AwareDatetime | None = None
    handler: Handler | None = None
    id: str
    kind: Annotated[
        EffectKind1
        | Literal['connector_sync']
        | Literal['decision']
        | Literal['turn_end'],
        Field(
            description="What kind of work an effect is. One enum for the wire and for the engine's\nown scheduling: a decision and a turn's end queue beside the calls and are\nswept the same way, so they are kinds too. Neither ever appears on an\n[`Effect`] — a decision rides the decision list, a turn end has no record.",
            title='EffectKind',
        ),
    ]
    name: str | None = None
    status: Annotated[EffectStatus1 | Literal['running'], Field(title='EffectStatus')]
    stream: bool | None = None
    tool_call_id: Annotated[
        str | None,
        Field(
            description='The model tool call a delegation answers; its own `id` is the child session.'
        ),
    ] = None


class InterruptResolution(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    payload: Any | None = None
    responder: InterruptResponder | None = None
    status: ResumeStatus


class McpServer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approve: Annotated[
        Approve1 | Literal['destructive'] | None,
        Field(
            description="Which of a connection's calls stop for a person.",
            title='Approve',
        ),
    ] = None
    auth_failure: AuthFailure | None = None
    path: Annotated[
        str,
        Field(
            description='Where a connection is declared: `mcp.<id>` or `plugin.<id>.mcp.<server>`'
        ),
    ]
    tools: Annotated[
        McpTools | None,
        Field(
            description='Narrows what the model sees. Absent ⇒ every tool the connection grants.'
        ),
    ] = None


class Reasoning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    blocks: list[Any] | None = None
    provider: ReasoningProvider
    text: str | None = None


class ReasoningConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effort: ReasoningEffort | None = None
    enabled: bool | None = None
    exclude: bool | None = None
    max_tokens: Annotated[int | None, Field(ge=0)] = None


class RetryConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    connector: RetryOverride | None = None
    default: RetryOverride | None = None
    llm: RetryOverride | None = None
    sub_agent: RetryOverride | None = None
    tool: RetryOverride | None = None


class StreamDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    finish_reason: str | None = None
    reasoning: str | None = None
    text: str | None = None
    tool_calls: list[ToolCallChunk] | None = None


class TokenDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    attempt: Annotated[int, Field(ge=0)]
    call_id: str
    finish_reason: str | None = None
    reasoning: str | None = None
    root_session_id: Annotated[str, Field(description='Transport routing key.')]
    seq: Annotated[
        int,
        Field(
            description='Per-call counter, distinct from event-store sequence.', ge=0
        ),
    ]
    session_id: Annotated[str, Field(description='May be a sub-agent of root.')]
    tenant_id: Annotated[
        str, Field(description='Tenant isolation key — subscribers must match.')
    ]
    text: str | None = None
    tool_calls: list[ToolCallChunk]
    turn_id: str | None = None


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    function: ToolCallFunction
    id: str
    type: str


class AgentConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    announce_mcp: Annotated[
        Announce | None,
        Field(
            description="Where the engine tells the model that an MCP server is available, and\nwhat that server says it is for.\n\nSeparate from `defer_tools`: a server exists whether or not its tools\nare deferred, and where a notice lands is a fact about this agent's\nprompt rather than about any server."
        ),
    ] = None
    defer_tools: Annotated[
        bool | DeferTools | None,
        Field(
            description='Defer every tool this agent offers, from any source, unless the tool or\nthe connection says otherwise. Absent ⇒ the agent defers nothing of its\nown; a connection may still defer on its own account.\n\nPresence is the switch, so an agent cannot carry settings that do\nnothing. Declared on the agent because an agent can hold this opinion\nbefore it names a connection: one that sets it gets the search tools\nfrom its first turn, so a connection added later costs no cache.'
        ),
    ] = None
    effort: Annotated[
        ReasoningEffort | None,
        Field(
            description='How hard the model thinks, carried on the agent because it pairs with\nthe model. Unset sends no reasoning config and leaves the provider its\nown default.'
        ),
    ] = None
    llm: Annotated[
        str | None, Field(description="The `[llm.*]` block this agent's calls run on.")
    ] = None
    mcp: Annotated[list[McpServer] | None, Field(description='MCP servers')] = None
    model: str
    plugins: Annotated[
        list[AgentPlugin] | None, Field(description='Plugins this agent uses.')
    ] = None
    retry: Annotated[
        RetryConfig | None,
        Field(
            description='Boxed: five per-kind overrides is a lot of bytes to carry inline\nthrough every command that holds a config.'
        ),
    ] = None
    sub_agents: Annotated[
        list[SubAgent] | None,
        Field(
            description='Sub-agents the model can delegate to. Presented to the model as tools (by\nid) alongside `tools`, but each call spawns a child session rather than\nexecuting a function.'
        ),
    ] = None
    system: str | None = None
    tools: Annotated[
        list[AgentTool] | None,
        Field(description='Worker- or client-executed tools the model can call.'),
    ] = None


class DraftMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str | list[StoredContent1 | StoredContent2 | StoredContent3] | None = None
    id: str | None = None
    name: str | None = None
    reasoning: Reasoning | None = None
    role: Role
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class LlmRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_completion_tokens: Annotated[int | None, Field(ge=0)] = None
    messages: list[DraftMessage]
    model: str
    reasoning: ReasoningConfig | None = None
    temperature: float | None = None
    tools: list[LlmTool] | None = None


class LlmResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str | None = None
    cost: Annotated[
        str | None,
        Field(
            description='Cost in dollars for this call, if the provider reports it. A decimal\nstring on the wire.',
            pattern='^-?\\d+(\\.\\d+)?$',
        ),
    ] = None
    finish_reason: str | None = None
    images: Annotated[
        list[ResponseImage] | None, Field(description='Images generated by the model.')
    ] = None
    model: str
    reasoning: Reasoning | None = None
    tool_calls: list[ToolCall] | None = None
    usage: Usage | None = None


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str | list[StoredContent1 | StoredContent2 | StoredContent3] | None = None
    id: str
    name: str | None = None
    reasoning: Reasoning | None = None
    role: Role
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class Node(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Message
    parent_id: str | None = None


class MessageTree(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    head_id: str | None = None
    nodes: list[Node]


class ClientInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    message: DraftMessage
    queue: Annotated[
        bool | None,
        Field(
            description='Hold this message for the next turn instead of refusing it when one\nis already running. Off by default: rejection stays the contract for\na plain submitter, and queuing is declared intent.'
        ),
    ] = None
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.message']


class ClientInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.messages']


class ClientInput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    client: ClientContext | None = None
    messages: list[DraftMessage]
    queue: Annotated[
        bool | None,
        Field(
            description='Hold this batch for the next turn instead of refusing it when one is\nalready running. Off by default: rejection stays the contract for a\nplain submitter, and queuing is declared intent.'
        ),
    ] = None
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.append']


class ClientPayload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: DraftMessage
    stream: bool | None = None
    type: Literal['client.message']


class ClientPayload2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    type: Literal['client.messages']


class ClientPayload3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    type: Literal['client.append']


class DecisionAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str | None = None
    llm: Annotated[
        str | None,
        Field(
            description="The `[llm.*]` block this call runs on; omitted ⇒ the merge source\nconfig's `llm`. Naming a different block moves one call to another\nvenue or vendor."
        ),
    ] = None
    max_completion_tokens: Annotated[int | None, Field(ge=0)] = None
    messages: list[DraftMessage] | None = None
    model: str | None = None
    reasoning: ReasoningConfig | None = None
    retry: Annotated[
        RetryOverride | None,
        Field(
            description="Layered over the agent config's `llm` policy, else over the engine's\ndefault."
        ),
    ] = None
    stream: bool | None = None
    temperature: float | None = None
    tools: list[LlmTool] | None = None
    type: Literal['llm.call']


class DecisionAction7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    message: Annotated[
        DraftMessage | None,
        Field(
            description="The child's opening message. It travels with the spawn, so it\ncannot race the creation of the session it opens."
        ),
    ] = None
    retry: Annotated[
        RetryOverride | None,
        Field(
            description="Layered over the agent config's `sub_agent` policy, else over the\nengine's default."
        ),
    ] = None
    session_id: str
    tool_call_id: Annotated[
        str,
        Field(
            description='The model tool-call this delegation answers — always required.'
        ),
    ]
    type: Literal['sub_agent.spawn']


class DecisionAction8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: DraftMessage
    session_id: str
    type: Literal['message.send']


class DecisionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: (
        list[
            DecisionAction1
            | DecisionAction2
            | DecisionAction3
            | DecisionAction4
            | DecisionAction5
            | DecisionAction6
            | DecisionAction7
            | DecisionAction8
            | DecisionAction9
            | DecisionAction10
            | DecisionAction11
            | DecisionAction12
        ]
        | None
    ) = None
    agent: Annotated[
        AgentConfig | None,
        Field(
            description='A new agent config write; omitted keeps the current config.'
        ),
    ] = None
    channels: Annotated[
        dict[str, Any] | None,
        Field(
            description='How each channel shows this decision, keyed by channel kind (e.g.\n`slack`). Opaque to the engine.'
        ),
    ] = None
    messages: list[DraftMessage] | None = None
    state: Annotated[
        Any,
        Field(
            description='Omitted or `null` keeps the current state; clear with a non-null empty value.'
        ),
    ] = None


class DecisionTrigger2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: Annotated[
        ClientContext,
        Field(
            description='Inputs the client declared on its run; the engine layers `client.tools`\nonto the proposed config by default.'
        ),
    ]
    messages: list[DraftMessage]
    new_from: Annotated[int, Field(ge=0)]
    type: Literal['client.messages']


class DecisionTrigger7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cost: Annotated[str | None, Field(pattern='^-?\\d+(\\.\\d+)?$')] = None
    error: ErrorInfo | None = None
    id: str
    message: DraftMessage | None = None
    ok: bool
    refused: Annotated[
        bool | None,
        Field(
            description='True when the model declined the request rather than answering it.\nA refusal reads as a turn that stopped well and said nothing, so\nwithout this the run continues from a blank answer.'
        ),
    ] = None
    truncated: bool
    type: Literal['llm.finished']
    usage: Usage | None = None


class DecisionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent: Annotated[
        AgentConfig | None,
        Field(
            description='The agent config resolved for the active path (`null` when none is set).'
        ),
    ] = None
    agent_id: str
    ancestry: list[str]
    attempts: Annotated[int, Field(ge=0)]
    calls: list[Effect]
    deadline: AwareDatetime | None = None
    decision_id: str
    identity: WorkerIdentity
    message_tree: MessageTree
    messages: list[Message]
    pending_calls: Annotated[
        int,
        Field(description='Count of in-flight `tool_call`/`sub_agent` calls.', ge=0),
    ]
    proposed: Annotated[
        DecisionResponse,
        Field(
            description="The engine's default continuation for `trigger` (empty when it needs\nworker knowledge). Advisory: accept by echoing it as the decision."
        ),
    ]
    session_id: str
    state: Annotated[
        Any,
        Field(
            description='Opaque worker state: JSON the engine stores but never interprets.',
            title='WorkerState',
        ),
    ]
    trigger: Annotated[
        DecisionTrigger1
        | DecisionTrigger2
        | DecisionTrigger3
        | DecisionTrigger4
        | DecisionTrigger5
        | DecisionTrigger6
        | DecisionTrigger7
        | DecisionTrigger8
        | DecisionTrigger9
        | DecisionTrigger10,
        Field(
            description="The trigger a worker sees on the wire — the materialized projection of the\nengine's internal decision trigger. It has no `ClientMessage`: a bare client\nmessage is always materialized to `ClientTranscript` by `to_wire_trigger`\n(`runtime::session::wire`) before delivery, so an unmaterialized message can\nnever reach a worker.",
            title='DecisionTrigger',
        ),
    ]
    turn_id: str | None = None


class SubstructureProtocol(BaseModel):
    client_input: Annotated[
        ClientInput1
        | ClientInput2
        | ClientInput3
        | ClientInput4
        | ClientInput5
        | ClientInput6
        | ClientInput7
        | None,
        Field(
            description='Everything a client can send on the input surface: submit a message / a full view / an\nappend batch / a named action, resume an interrupt, or settle a client tool. A flat,\ninternally-tagged union — its seven tags produce serde\'s "unknown variant, expected one\nof …" error for free. `Runtime::handle_client_input` is the single seam that dispatches\nit (mirroring `resolve_response` on the worker side).\n\nAddressing lives where it is meaningful, not in a shared envelope: `agent_id` (routes\nthe turn, creating the session if new) and the optional idempotency `turn_id` are\nfields of the four submit variants only. A resume/settle addresses an interrupt/effect\nid and continues whatever turn is active, so it carries neither — misplacing them is\nunrepresentable rather than rejected. `session_id` is the one universal address and\nrides the envelope. A submit\'s body rebuilds a [`ClientPayload`] at the seam.',
            title='ClientInput',
        ),
    ] = None
    client_payload: Annotated[
        ClientPayload1 | ClientPayload2 | ClientPayload3 | ClientPayload4 | None,
        Field(
            description='The client→engine inbound *submit* wire form: an untrusted client submits a message,\nits full conversation view, an append batch, or a named action. Lowered to domain events at the\n`SubmitClientPayload` command seam (`runtime::session::command`); never persisted\nas-is. Carried verbatim inside [`ClientInput`], which is the full client input\nsurface.',
            title='ClientPayload',
        ),
    ] = None
    decision_request: DecisionRequest | None = None
    decision_response: DecisionResponse | None = None
    interrupt_payload: InterruptPayload | None = None
    interrupt_resolution: InterruptResolution | None = None
    stream_delta: StreamDelta | None = None
    token_delta: TokenDelta | None = None
