# generated by datamodel-codegen:
#   filename:  protocol.schema.json
#   timestamp: 2026-07-16T09:13:01+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class AudioData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: str
    format: str


class ClientInput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    args: Any | None = None
    name: str
    turn_id: str | None = None
    type: Literal['client.action']


class ClientInput4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resume']


class ClientInput5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0) | None = None
    id: str
    result: Any | None = None
    type: Literal['tool.result']


class ClientInput6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0) | None = None
    error: str
    id: str
    retryable: bool
    type: Literal['tool.error']


class ClientPayload3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any | None = None
    name: str
    type: Literal['client.action']


class ContentPart1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    type: Literal['text']


class ContentPart4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_audio: AudioData
    type: Literal['input_audio']


class DecisionAction3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0) | None = None
    id: str | None = None
    result: Any
    type: Literal['tool.result']


class DecisionAction4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0) | None = None
    id: str | None = None
    response: Any = Field(
        ...,
        description="A neutral `LlmResponse`, or the provider's native response when the\nanswered `llm.execute` carried a `format`.",
    )
    type: Literal['llm.result']


class DecisionAction9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str | None = None
    payload: Any | None = None
    reason: str
    type: Literal['interrupt']


class DecisionAction10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: Any | None = None
    type: Literal['done']


class DecisionTrigger1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['session.start']


class DecisionTrigger3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    args: Any | None = None
    name: str
    type: Literal['client.action']


class DecisionTrigger5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str | None = None
    id: str
    name: str
    ok: bool
    result: str | None = None
    type: Literal['tool.finished']


class DecisionTrigger8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    error: str | None = None
    id: str
    ok: bool
    result: str | None = None
    session_id: str
    type: Literal['sub_agent.finished']


class DecisionTrigger9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    interrupt_id: str
    payload: Any | None = None
    type: Literal['interrupt.resumed']


class EffectKind(Enum):
    tool_call = 'tool_call'
    sub_agent = 'sub_agent'
    llm_call = 'llm_call'


class EffectStatus(Enum):
    pending = 'pending'
    completed = 'completed'
    failed = 'failed'
    retry_scheduled = 'retry_scheduled'
    queued = 'queued'


class ErrorCode(Enum):
    provider_error = 'provider_error'
    rate_limited = 'rate_limited'
    refused = 'refused'
    budget_exceeded = 'budget_exceeded'
    deadline_exceeded = 'deadline_exceeded'


class FileData(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file_data: str
    filename: str


class Handler(Enum):
    server = 'server'
    worker = 'worker'
    client = 'client'


class ImageUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class InterruptOrigin(Enum):
    system = 'system'
    machine = 'machine'
    frontend = 'frontend'


class LlmFormat(Enum):
    openai = 'openai'
    anthropic = 'anthropic'


class LlmTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str
    input: Any | None = Field(
        None,
        description="JSON Schema for the tool's arguments; omitted declares a no-argument\ntool. The engine validates each call's arguments against it and hands\nproviders their native form.",
    )
    name: str
    output: Any | None = Field(
        None,
        description='JSON Schema the settled result must satisfy; never sent to the model.\nA violating result settles as a terminal tool error.',
    )


class ReasoningEffort(Enum):
    xhigh = 'xhigh'
    high = 'high'
    medium = 'medium'
    low = 'low'
    minimal = 'minimal'
    none = 'none'


class ResponseImage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class RetryPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backoff_base_secs: conint(ge=0)
    backoff_max_secs: conint(ge=0)
    max_retries: conint(ge=0)
    timeout_secs: conint(ge=0) | None = None


class Role(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class SubAgent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    id: str


class ToolCallChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str | None = None
    id: str
    name: str | None = None


class ToolCallFunction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str
    name: str


class ToolInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['valid']
    value: Any


class ToolInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str
    status: Literal['invalid']
    value: Any


class ToolInput3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str
    status: Literal['malformed']


class ToolInput(RootModel[ToolInput1 | ToolInput2 | ToolInput3]):
    root: ToolInput1 | ToolInput2 | ToolInput3 = Field(
        ...,
        description="The engine's classification of a tool call's arguments, delivered on the\n`tool.execute` trigger alongside the raw `arguments` string. Always on the\nwire — absence never carries meaning.",
        title='ToolInput',
    )


class VideoUrl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    url: str


class WorkerIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str | None = None
    metadata: dict[str, str] | None = None


class WorkerState(RootModel[Any]):
    root: Any = Field(
        ...,
        description='Opaque worker state: JSON the engine stores but never interprets.',
        title='WorkerState',
    )


class AgentTool(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: str | None = None
    handler: Handler | None = None
    input: Any | None = None
    name: str
    output: Any | None = None


class ClientContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context: list[Any] | None = None
    forwarded_props: Any | None = None
    state: Any | None = None
    tools: list[AgentTool] | None = None


class ContentPart2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image_url: ImageUrl
    type: Literal['image_url']


class ContentPart3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    file: FileData
    type: Literal['file']


class ContentPart5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['video_url']
    video_url: VideoUrl


class ContentPart(
    RootModel[ContentPart1 | ContentPart2 | ContentPart3 | ContentPart4 | ContentPart5]
):
    root: ContentPart1 | ContentPart2 | ContentPart3 | ContentPart4 | ContentPart5 = (
        Field(..., title='ContentPart')
    )


class DecisionAction2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: Any
    handler: Handler | None = Field(
        None, description='`worker` or `client`; omitted ⇒ `worker`.'
    )
    id: str | None = None
    name: str
    retry: RetryPolicy | None = None
    type: Literal['tool.call']


class DecisionAction5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0) | None = None
    code: ErrorCode | None = None
    detail: Any | None = None
    error: str
    id: str | None = None
    retryable: bool | None = Field(None, description='Omitted ⇒ terminal.')
    type: Literal['tool.error']


class DecisionAction6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0) | None = None
    code: ErrorCode | None = None
    detail: Any | None = None
    error: str
    id: str | None = None
    retryable: bool | None = Field(None, description='Omitted ⇒ terminal.')
    type: Literal['llm.error']


class DecisionAction7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    retry: RetryPolicy | None = None
    session_id: str
    tool_call_id: str = Field(
        ...,
        description='The model tool-call this delegation answers — always required.',
    )
    type: Literal['sub_agent.spawn']


class DecisionTrigger4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    arguments: str
    attempt: conint(ge=0)
    deadline: AwareDatetime | None = None
    id: str
    input: ToolInput = Field(
        ...,
        description="The engine's classification of `arguments` against the tool's\ndeclared `input` schema: `valid` (with the parsed `value`),\n`invalid` (value plus the violation), or `malformed` (not a JSON\nobject). Always on the wire.",
    )
    name: str
    type: Literal['tool.execute']


class DecisionTrigger6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt: conint(ge=0)
    deadline: AwareDatetime | None = None
    format: LlmFormat | None = None
    id: str
    request: Any = Field(
        ...,
        description="The neutral `LlmRequest` JSON, or the provider's native request body\nwhen `format` is set.",
    )
    stream: bool | None = None
    type: Literal['llm.execute']


class Effect(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str | None = None
    anchor: str | None = Field(
        None, description='The tree node the effect was requested at.'
    )
    arguments: str | None = None
    attempt: conint(ge=0)
    deadline: AwareDatetime | None = None
    handler: Handler | None = None
    id: str
    kind: EffectKind
    name: str | None = None
    session_id: str | None = None
    status: EffectStatus
    stream: bool | None = None


class ReasoningConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effort: ReasoningEffort | None = None
    enabled: bool | None = None
    exclude: bool | None = None
    max_tokens: conint(ge=0) | None = None


class StreamDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    finish_reason: str | None = None
    reasoning: str | None = None
    text: str | None = None
    tool_calls: list[ToolCallChunk] | None = None


class TokenDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    attempt: conint(ge=0)
    call_id: str
    finish_reason: str | None = None
    reasoning: str | None = None
    root_session_id: str = Field(..., description='Transport routing key.')
    seq: conint(ge=0) = Field(
        ..., description='Per-call counter, distinct from event-store sequence.'
    )
    session_id: str = Field(..., description='May be a sub-agent of root.')
    tenant_id: str = Field(
        ..., description='Tenant isolation key — subscribers must match.'
    )
    text: str | None = None
    tool_calls: list[ToolCallChunk] | None = None
    turn_id: str | None = None


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    function: ToolCallFunction
    id: str
    type: str


class AgentConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    format: LlmFormat | None = Field(
        None,
        description='Provider wire format for worker-handled calls; requires `handler:\nworker`. Absent ⇒ the neutral format.',
    )
    handler: Handler | None = Field(
        None,
        description="Where the proposed LLM call runs: `Some(Worker)` ⇒ the worker executes it\n(answering `llm.execute`); absent or `Some(Server)` ⇒ the engine's\nserver-side provider. `client` is invalid and rejected at the decision seam.",
    )
    model: str
    retry: RetryPolicy | None = None
    stream: bool | None = None
    sub_agents: list[SubAgent] | None = Field(
        None,
        description='Sub-agents the model can delegate to. Presented to the model as tools (by\nid) alongside `tools`, but each call spawns a child session rather than\nexecuting a function.',
    )
    system: str | None = None
    tools: list[AgentTool] | None = Field(
        None, description='Worker- or client-executed tools the model can call.'
    )


class Content(RootModel[str | list[ContentPart]]):
    root: str | list[ContentPart] = Field(
        ...,
        description='Message content: either a plain string or an array of typed parts.\nSerializes as a raw string or array respectively (untagged).',
        title='Content',
    )


class DraftMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: Content | None = None
    id: str | None = None
    name: str | None = None
    role: Role
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class LlmRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    max_completion_tokens: conint(ge=0) | None = None
    messages: list[DraftMessage]
    model: str
    reasoning: ReasoningConfig | None = None
    temperature: float | None = None
    tools: list[LlmTool] | None = None


class LlmResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str | None = None
    cost: constr(pattern=r'^-?\d+(\.\d+)?$') | None = Field(
        None,
        description='Cost in dollars for this call, if the provider reports it. A decimal\nstring on the wire.',
    )
    finish_reason: str | None = None
    images: list[ResponseImage] | None = Field(
        None, description='Images generated by the model.'
    )
    model: str
    tool_calls: list[ToolCall] | None = None
    usage: Any | None = None


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: Content | None = None
    id: str
    name: str | None = None
    role: Role
    tool_call_id: str | None = None
    tool_calls: list[ToolCall] | None = None


class Node(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: Message
    parent_id: str | None = None


class MessageTree(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    head_id: str | None = None
    nodes: list[Node] | None = None


class ClientInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    message: DraftMessage
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.message']


class ClientInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent_id: str
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    turn_id: str | None = None
    type: Literal['client.messages']


class ClientInput(
    RootModel[
        ClientInput1
        | ClientInput2
        | ClientInput3
        | ClientInput4
        | ClientInput5
        | ClientInput6
    ]
):
    root: (
        ClientInput1
        | ClientInput2
        | ClientInput3
        | ClientInput4
        | ClientInput5
        | ClientInput6
    ) = Field(
        ...,
        description='Everything a client can send on the input surface: submit a message / a full view / a\nnamed action, resume an interrupt, or settle a client tool. A flat, internally-tagged\nunion — its six tags produce serde\'s "unknown variant, expected one of …" error for\nfree. `Runtime::handle_client_input` is the single seam that dispatches it (mirroring\n`resolve_response` on the worker side).\n\nAddressing lives where it is meaningful, not in a shared envelope: `agent_id` (routes\nthe turn, creating the session if new) and the optional idempotency `turn_id` are\nfields of the three submit variants only. A resume/settle addresses an interrupt/effect\nid and continues whatever turn is active, so it carries neither — misplacing them is\nunrepresentable rather than rejected. `session_id` is the one universal address and\nrides the envelope. A submit\'s body rebuilds a [`ClientPayload`] at the seam.',
        title='ClientInput',
    )


class ClientPayload1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: DraftMessage
    stream: bool | None = None
    type: Literal['client.message']


class ClientPayload2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: ClientContext | None = None
    messages: list[DraftMessage]
    stream: bool | None = None
    type: Literal['client.messages']


class ClientPayload(RootModel[ClientPayload1 | ClientPayload2 | ClientPayload3]):
    root: ClientPayload1 | ClientPayload2 | ClientPayload3 = Field(
        ...,
        description='The client→engine inbound *submit* wire form: an untrusted client submits a message,\nits full conversation view, or a named action. Lowered to domain events at the\n`SubmitClientPayload` command seam (`runtime::session::command`); never persisted\nas-is. Carried verbatim inside [`ClientInput`], which is the full client input\nsurface.',
        title='ClientPayload',
    )


class DecisionAction1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    handler: Handler | None = Field(
        None, description='`server` or `worker`; omitted ⇒ `server`.'
    )
    id: str | None = None
    max_completion_tokens: conint(ge=0) | None = None
    messages: list[DraftMessage] | None = None
    model: str | None = None
    reasoning: ReasoningConfig | None = None
    retry: RetryPolicy | None = None
    stream: bool | None = None
    temperature: float | None = None
    tools: list[LlmTool] | None = None
    type: Literal['llm.call']


class DecisionAction8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    message: DraftMessage
    session_id: str
    type: Literal['message.send']


class DecisionAction(
    RootModel[
        DecisionAction1
        | DecisionAction2
        | DecisionAction3
        | DecisionAction4
        | DecisionAction5
        | DecisionAction6
        | DecisionAction7
        | DecisionAction8
        | DecisionAction9
        | DecisionAction10
    ]
):
    root: (
        DecisionAction1
        | DecisionAction2
        | DecisionAction3
        | DecisionAction4
        | DecisionAction5
        | DecisionAction6
        | DecisionAction7
        | DecisionAction8
        | DecisionAction9
        | DecisionAction10
    ) = Field(
        ...,
        description="The action a worker authors on the wire. Mirrors the internal `Action`, but a\nsettle's effect id may be omitted: on the sync/pull paths the answered\n`*.execute` trigger names it, so echoing it is redundant. `resolve_response`\n(`runtime::session::wire`) turns this into the internal `Action` (id always\npresent) at the transport boundary.",
        title='DecisionAction',
    )


class DecisionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actions: list[DecisionAction] | None = None
    agent: AgentConfig | None = Field(
        None, description='A new agent config write; omitted keeps the current config.'
    )
    messages: list[DraftMessage] | None = None
    state: WorkerState | None = Field(
        None,
        description='Omitted or `null` keeps the current state; clear with a non-null empty value.',
    )


class DecisionTrigger2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    client: ClientContext | None = Field(
        None,
        description='Inputs the client declared on its run; the engine layers `client.tools`\nonto the proposed config by default.',
    )
    messages: list[DraftMessage]
    new_from: conint(ge=0) | None = None
    type: Literal['client.messages']


class DecisionTrigger7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: ErrorCode | None = None
    cost: constr(pattern=r'^-?\d+(\.\d+)?$') | None = None
    detail: Any | None = None
    error: str | None = None
    id: str
    message: DraftMessage | None = None
    ok: bool
    truncated: bool | None = None
    type: Literal['llm.finished']
    usage: Any | None = None


class DecisionTrigger(
    RootModel[
        DecisionTrigger1
        | DecisionTrigger2
        | DecisionTrigger3
        | DecisionTrigger4
        | DecisionTrigger5
        | DecisionTrigger6
        | DecisionTrigger7
        | DecisionTrigger8
        | DecisionTrigger9
    ]
):
    root: (
        DecisionTrigger1
        | DecisionTrigger2
        | DecisionTrigger3
        | DecisionTrigger4
        | DecisionTrigger5
        | DecisionTrigger6
        | DecisionTrigger7
        | DecisionTrigger8
        | DecisionTrigger9
    ) = Field(
        ...,
        description="The trigger a worker sees on the wire — the materialized projection of the\nengine's internal decision trigger. It has no `ClientMessage`: a bare client\nmessage is always materialized to `ClientTranscript` by `to_wire_trigger`\n(`runtime::session::wire`) before delivery, so an unmaterialized message can\nnever reach a worker.",
        title='DecisionTrigger',
    )


class DecisionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agent: AgentConfig | None = Field(
        None,
        description='The agent config resolved for the active path (`null` when none is set).',
    )
    agent_id: str
    ancestry: list[str]
    attempts: conint(ge=0)
    calls: list[Effect]
    deadline: AwareDatetime | None = None
    decision_id: str
    identity: WorkerIdentity
    message_tree: MessageTree
    messages: list[Message]
    pending_calls: conint(ge=0) = Field(
        ..., description='Count of in-flight `tool_call`/`sub_agent` calls.'
    )
    proposed: DecisionResponse | None = Field(
        None,
        description="The engine's default continuation for `trigger` (`null` when it needs\nworker knowledge). Advisory: accept by echoing it as the decision.",
    )
    session_id: str
    state: WorkerState
    trigger: DecisionTrigger
    turn_id: str | None = None


class SubstructureProtocol(BaseModel):
    client_input: ClientInput | None = None
    client_payload: ClientPayload | None = None
    decision_request: DecisionRequest | None = None
    decision_response: DecisionResponse | None = None
    stream_delta: StreamDelta | None = None
    token_delta: TokenDelta | None = None
