use std::sync::Arc;

use async_trait::async_trait;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};

use crate::runtime::owner::SessionOwner;
use crate::runtime::session::message::{Message, ToolCall};

/// An image returned by the model in the response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResponseImage {
    pub url: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmToolFunction {
    pub name: String,
    pub description: String,
    pub parameters: serde_json::Value,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmTool {
    pub function: LlmToolFunction,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmRequest {
    pub model: String,
    pub messages: Vec<Message>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<LlmTool>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_completion_tokens: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<ReasoningConfig>,
}

/// Reasoning ("thinking") controls, mirroring OpenRouter's `reasoning` param.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReasoningConfig {
    /// OpenAI / Grok style. Mutually exclusive with `max_tokens`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub effort: Option<ReasoningEffort>,
    /// Anthropic / Gemini / Qwen style token budget. Mutually exclusive with `effort`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,
    /// Reason internally but omit the reasoning from the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub exclude: Option<bool>,
    /// Enable reasoning at the provider's default (medium) effort.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ReasoningEffort {
    Xhigh,
    High,
    Medium,
    Low,
    Minimal,
    None,
}

/// Normalized LLM response. Provider adapters convert their raw responses
/// into this type at the boundary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LlmResponse {
    pub model: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tool_calls: Vec<ToolCall>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finish_reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<serde_json::Value>,
    /// Cost in dollars for this call, if the provider reports it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost: Option<Decimal>,
    /// Images generated by the model.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub images: Vec<ResponseImage>,
}

/// Trait for LLM client providers (resolved by the runtime).
#[async_trait]
pub trait LlmProviderTrait: Send + Sync {
    async fn resolve(&self, owner: &SessionOwner) -> Result<Arc<dyn LlmCallable>, String>;
}

#[derive(Debug, Clone)]
pub struct CallContext<'a> {
    pub session_id: &'a str,
    pub tenant_id: &'a str,
    pub agent_id: &'a str,
    pub call_id: &'a str,
    pub attempt: u32,
    pub owner: &'a SessionOwner,
    /// Parent chain, root-last. Empty for top-level sessions.
    pub ancestry: &'a [String],
}

/// Trait for calling an LLM (single call or streaming).
#[async_trait]
pub trait LlmCallable: Send + Sync + 'static {
    async fn call(
        &self,
        request: &LlmRequest,
        ctx: &CallContext<'_>,
    ) -> Result<LlmResponse, LlmCallError>;

    /// Streaming variant — sends deltas through `tx` while the call is
    /// in progress, then returns the final assembled response.
    /// Default implementation ignores the channel and delegates to `call()`.
    async fn call_streaming(
        &self,
        request: &LlmRequest,
        ctx: &CallContext<'_>,
        _tx: tokio::sync::mpsc::UnboundedSender<StreamDelta>,
    ) -> Result<LlmResponse, LlmCallError> {
        self.call(request, ctx).await
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCode {
    ProviderError,
    RateLimited,
    Refused,
    BudgetExceeded,
    DeadlineExceeded,
}

#[derive(Debug, Clone)]
pub struct LlmCallError {
    pub message: String,
    pub retryable: bool,
    pub code: Option<ErrorCode>,
    pub detail: Option<serde_json::Value>,
}

/// A transient streaming delta from a provider's in-progress call. Each field is
/// independent; a chunk may carry any combination.
#[derive(Debug, Clone, Default)]
pub struct StreamDelta {
    pub text: Option<String>,
    /// Reasoning/thinking text (transient; not persisted).
    pub reasoning: Option<String>,
    /// Tool-call fragments; every chunk carries the call's stable id.
    pub tool_calls: Vec<ToolCallChunk>,
    pub finish_reason: Option<String>,
}

/// One tool call's incremental contribution within a [`StreamDelta`]. The first
/// chunk carries `id` + `name`; later chunks carry the same `id` and more `arguments`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallChunk {
    pub id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}
